---
- ros_topic_name: "/cmd/thrust"
  gz_topic_name: "/model/my_lrauv/joint/propeller_joint/cmd_thrust"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
  
- ros_topic_name: "/cmd/vertical_fins"
  gz_topic_name: "/model/my_lrauv/joint/vertical_fins_joint/0/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
  
  
- gz_topic_name: "/imu"
  ros_topic_name: "/imu/data"
  gz_type_name: "gz.msgs.IMU"
  ros_type_name: "sensor_msgs/msg/Imu"
  direction: GZ_TO_ROS
  
 
- gz_topic_name: "/model/my_lrauv/odometry"
  ros_topic_name: "/odom"
  gz_type_name: "gz.msgs.Odometry"
  ros_type_name: "nav_msgs/msg/Odometry"
  direction: GZ_TO_ROS
  

  
  

